# VM Configuration File
# ----------------------

# Mode selection:
#   1 = Single Cycle
#   2 = Pipelined
#   3 = Hazard Detection
#   4 = Forwarding
#   5 = Static Branch Prediction
#   6 = Dynamic Branch Prediction

mode = 1